name: バグ報告 (Bug Report)
description: システムの不具合やエラーの報告
title: "[バグ] "
labels: ["bug", "claude-task"]
body:
  - type: markdown
    attributes:
      value: |
        ## バグ報告テンプレート
        
        このテンプレートはClaudeによる修正を前提としています。
        バグ修正と同時に関連ドキュメントの更新も行われます。

  - type: textarea
    id: bug-description
    attributes:
      label: バグの概要
      description: 発生している問題について詳しく説明してください
      placeholder: |
        例：
        - アンケート投票後に結果が表示されない
        - WebSocket接続が頻繁に切断される
        - プレゼンテーション画面が正しく更新されない
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 再現手順
      description: バグを再現するための詳細な手順を記述してください
      placeholder: |
        1. プレゼンテーション画面を開く
        2. アンケートを開始する
        3. 観客画面から投票を行う
        4. 結果が表示されない
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待される動作
      description: 正常に動作する場合の期待される挙動を説明してください
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 実際の動作
      description: 現在発生している問題の詳細な挙動を説明してください
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 重要度
      description: このバグの重要度を選択してください
      options:
        - 致命的 (システムが使用不可)
        - 高 (主要機能に影響)
        - 中 (一部機能に影響)
        - 低 (軽微な問題)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 影響を受けるコンポーネント
      description: バグが発生しているシステムの部分を選択してください
      options:
        - フロントエンド (frontend/)
        - バックエンド (backend/)
        - インフラ (infra/)
        - WebSocket通信
        - データベース
        - システム全体
        - 不明
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 環境情報
      description: バグが発生している環境について詳しく記述してください
      placeholder: |
        - OS: Windows 10 / macOS / Linux
        - ブラウザ: Chrome 120.0.0 / Firefox 121.0 / Safari 17.0
        - Node.js バージョン: v18.17.0
        - 開発/本番環境: development/production
        - Docker使用: Yes/No

  - type: textarea
    id: error-logs
    attributes:
      label: エラーログ・スクリーンショット
      description: |
        関連するエラーログ、コンソール出力、スクリーンショットがあれば添付してください
      placeholder: |
        ```
        Error: WebSocket connection failed
        at WebSocketClient.connect (src/socket/client.ts:45)
        ...
        ```

  - type: textarea
    id: additional-context
    attributes:
      label: 追加情報
      description: その他の参考情報、関連issue、ワークアラウンドなど

  - type: textarea
    id: documentation-updates
    attributes:
      label: 更新が必要なドキュメント
      description: このバグ修正に伴って更新すべきドキュメントを指定してください
      placeholder: |
        - doc/troubleshooting.md - トラブルシューティング情報の追加
        - README.md - 既知の問題・制限事項の更新
        - doc/architecture.md - システム構成の修正

  - type: checkboxes
    id: checklist
    attributes:
      label: 確認事項
      description: 以下の項目を確認してください
      options:
        - label: バグを再現可能である
          required: true
        - label: 関連するエラーログを確認した
          required: false
        - label: 既存のissueで同様の問題が報告されていないことを確認した
          required: true

  - type: markdown
    attributes:
      value: |
        ## Claude修正時の注意点
        
        - **日本語出力**: 全てのコメント、ログ、出力は日本語で行ってください
        - **リアルタイム性**: プレゼンテーション中の使用を考慮し、迅速な修正を心がけてください
        - **テスト**: 修正後は必ず動作確認とテストを実施してください
        - **ドキュメント更新**: バグ修正と同時に関連ドキュメントも必ず更新してください
        - **予防策**: 同様のバグを防ぐための改善策も検討してください